--
-- PostgreSQL database dump
--

\restrict 9wH1cN6tQnXnKbcvYoIwsLbSUuquYKxCPgObK6KdnR2mas2He21AnqMibbD1TEI

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: templates; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (8, 'ใบอนุญาตจัดตั้งสมาคมหรือองค์การ', '[["ใบอนุญาตจัดตั้งสมาคมหรือองค์การ"], ["เลขอนุญาตที่", "ได้ขออนุญาตจัดตั้ง"]]', NULL, NULL, NULL, 'เอกสารจัดตั้งมูลนิธิ', true, true, 7, NULL, '2025-12-17 16:24:12.325928', '2025-12-17 17:22:23.962207');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (9, 'แก้ไขเพิ่มเติมข้อบังคับของมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 8, NULL, '2025-12-17 16:24:12.327758', '2025-12-17 17:22:23.975112');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (3, 'ตราสารฉบับที่2', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 2, NULL, '2025-12-17 16:24:12.311279', '2025-12-17 17:22:23.893778');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (4, 'ตราสารฉบับที่3', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 3, NULL, '2025-12-17 16:24:12.31534', '2025-12-17 17:22:23.908077');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (5, 'ประกาศกระทรวงมหาดไทยให้อำนาจจัดตั้งมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารจัดตั้งมูลนิธิ', false, true, 4, NULL, '2025-12-17 16:24:12.319743', '2025-12-17 17:22:23.922594');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (6, 'ใบสำคัญแสดงการจดทะเบียนจัดตั้งมูลนิธิ', '[["ใบสำคัญแสดงการจดทะเบียนจัดตั้งมูลนิธิ"], ["ม.น. 3", "ใบสำคัญ"]]', NULL, NULL, NULL, 'เอกสารจัดตั้งมูลนิธิ', true, true, 5, NULL, '2025-12-17 16:24:12.321838', '2025-12-17 17:22:23.935768');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (10, 'ข้อบังคับที่ขอจดทะเบียนเปลี่ยนแปลง', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 9, NULL, '2025-12-17 16:24:12.329046', '2025-12-17 17:22:23.988711');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (11, 'รายละเอียดข้อบังคับที่ขอจดทะเบียนเปลี่ยนแปลง', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 10, NULL, '2025-12-17 16:24:12.329976', '2025-12-17 17:22:24.00272');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (12, 'เอกสารเปลี่ยนแปลงมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 11, NULL, '2025-12-17 16:24:12.330687', '2025-12-17 17:22:24.01827');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (14, 'ประกาศนายทะเบียนเรื่องจดทะเบียนแก้ไขเพิ่มเติมข้อบังคับมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 13, NULL, '2025-12-17 16:24:12.332272', '2025-12-17 17:22:24.043562');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (15, 'ขออนุญาตจดทะเบียนแก้ไขเพิ่มเติมข้อบังคับของมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 14, NULL, '2025-12-17 16:24:12.333174', '2025-12-17 17:22:24.05607');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (16, 'ขออณุญาตจดทะเบียนแต่งตั้งกรรมการขึ้นใหม่ทั้งชุดและแก้ไขเพิ่มเติมข้อบังคับของมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 15, NULL, '2025-12-17 16:24:12.33392', '2025-12-17 17:22:24.068123');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (17, 'บันทึกข้อความขออนุญาตจดทะเบียนเปลี่ยนแปลงกรรมการมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 16, NULL, '2025-12-17 16:24:12.335511', '2025-12-17 17:22:24.079731');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (19, 'ขออนุญาตจดทะเบียนเปลี่ยนแปลงกรรมการมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 18, NULL, '2025-12-17 16:24:12.337397', '2025-12-17 17:22:24.103819');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (21, 'เรื่องราวขออนุญาตจดทะเบียนการเปลี่ยนแปลงมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 20, NULL, '2025-12-17 16:24:12.339196', '2025-12-17 17:22:24.135929');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (23, 'รายงานการประชุมสามัญ', NULL, NULL, NULL, NULL, 'เอกสารการประชุม', false, true, 22, NULL, '2025-12-17 16:24:12.340716', '2025-12-17 17:22:24.166186');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (25, 'บันทึกการประชุม', NULL, NULL, NULL, NULL, 'เอกสารการประชุม', false, true, 24, NULL, '2025-12-17 16:24:12.342897', '2025-12-17 17:22:24.191489');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (26, 'ระเบียบวาระการประชุม', NULL, NULL, NULL, NULL, 'เอกสารการประชุม', false, true, 25, NULL, '2025-12-17 16:24:12.343662', '2025-12-17 17:22:24.202939');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (27, 'หนังสือรับรองบุคคลดำเนินการ', NULL, NULL, NULL, NULL, NULL, false, true, 26, NULL, '2025-12-17 16:24:12.34444', '2025-12-17 17:22:24.21535');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (28, 'บันทึกคำให้การของบุคคลผู้จะเป็นกรรมการของมูลนิธิ', NULL, NULL, NULL, NULL, NULL, false, true, 27, NULL, '2025-12-17 16:24:12.345278', '2025-12-17 17:22:24.231357');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (29, 'รายงานของผู้สอบบัญชีรับอนุญาต', NULL, NULL, NULL, NULL, 'เอกสารบัญชี', false, true, 28, NULL, '2025-12-17 16:24:12.346067', '2025-12-17 17:22:24.243707');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (30, 'รายละเอียดการตรวจสอบบัญชีงบดุล', NULL, NULL, NULL, NULL, 'เอกสารบัญชี', false, true, 29, NULL, '2025-12-17 16:24:12.346819', '2025-12-17 17:22:24.256025');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (31, 'รายละเอียดการตรวจสอบบัญชีงบรายรับรายจ่าย', NULL, NULL, NULL, NULL, 'เอกสารบัญชี', false, true, 30, NULL, '2025-12-17 16:24:12.348078', '2025-12-17 17:22:24.269172');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (32, 'รายละเอียดการเปลี่ยนแปลงมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 31, NULL, '2025-12-17 16:24:12.349124', '2025-12-17 17:22:24.282143');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (33, 'บันทึกข้อความสอบสวนคุณสมบัติกรรมการมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารสอบสวน', false, true, 32, NULL, '2025-12-17 16:24:12.350075', '2025-12-17 17:22:24.296138');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (34, 'บันทึกข้อความประกาศยกเลิกมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารยกเลิกมูลนิธิ', false, true, 33, NULL, '2025-12-17 16:24:12.350888', '2025-12-17 17:22:24.308778');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (35, 'บันทึกข้อความแจ้งเลิกมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารยกเลิกมูลนิธิ', false, true, 34, NULL, '2025-12-17 16:24:12.351713', '2025-12-17 17:22:24.321196');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (22, 'เอกสารยกเลิกมูลนิธิ', '[["ขออนุญาตจดทะเบียนเลิกมูลนิธิ"], ["แจ้งการเลิกมูลนิธิ"], ["ขอยกเลิกมูลนิธิ"], ["ขอส่งการเลิกมูลนิธิ"]]', NULL, NULL, NULL, 'เอกสารยกเลิกมูลนิธิ', true, true, 21, NULL, '2025-12-17 16:24:12.339933', '2025-12-17 17:30:13.519285');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (2, 'บัญชีรายชื่อกรรมการมูลนิธิ', '[["บัญชีรายชื่อ", "กรรมการ"], ["บัญชีรายละเอียดกรรมการ"], ["บัญชี", "กรรมการมูลนิธิ"], ["บัญชีอัตราการมูลนิธิ"], ["บัญชีการมูลนิธิ"], ["ลำดับที่", "ชื่อ-สกุล", "ตำแหน่ง"]]', NULL, '[["ประมวลกฎหมายแพ่งและพาณิชย์"], ["ให้มูลนิธิยื่น"], ["ขออนุญาตจดทะเบียน"]]', NULL, NULL, true, true, 1, NULL, '2025-12-17 16:24:12.309364', '2025-12-17 17:22:23.877482');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (24, 'รายงานการประชุม', '[["รายงานการประชุม", "คณะกรรมการ", "ครั้งที่"], ["รายงานการประชุม", "ระเบียบวาระ"], ["รายงานการประชุม", "รายชื่อผู้มาประชุม"]]', '[["เลิกประชุม", "ลงชื่อ", "ผู้บันทึกการประชุม"], ["เลิกประชุม", "ขอรับรองว่ารายงานการประชุมนี้ถูกต้อง"], ["ประธานการประชุม", "ลงชื่อ"], ["ปิดประชุมเวลา", "ผู้จัดรายงานการประชุม"], ["ปิดประชุมเวลา", "กรรมการและเลขานุการ"], ["มติ", "ปิดประชุมเวลา"], ["ผู้จัดรายงานการประชุม", "ลงชื่อ"]]', NULL, NULL, 'เอกสารการประชุม', false, true, 23, NULL, '2025-12-17 16:24:12.342103', '2025-12-17 17:22:24.179878');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (37, 'ขออนุญาตจดทะเบียนจัดตั้งมูลนิธิ', '[["ขออนุญาตจดทะเบียนจัดตั้งมูลนิธิ"]]', '[["ให้มูลนิธิยื่นคำขอมีเลขประจำตัวผู้เสียภาษี"], ["ประมวลรัษฎากร", "รอบระยะเวลาบัญชี"], ["รายงานการดำเนินกิจการต่อนายทะเบียน"]]', NULL, NULL, 'เอกสารจัดตั้ง', false, true, 37, NULL, '2025-12-17 16:34:32.712738', '2025-12-17 16:43:51.073917');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (36, 'ประกาศนายทะเบียนยกเลิกมูลนิธิ', NULL, NULL, NULL, NULL, 'เอกสารยกเลิกมูลนิธิ', false, true, 35, NULL, '2025-12-17 16:24:12.352811', '2025-12-17 17:22:24.332375');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (38, 'หนังสือให้อำนาจและรายละเอียดการเปลี่ยนแปลง(จัดตั้ง)', '[["ม.น. 2", "หนังสือให้อำนาจจัดตั้ง"], ["บัญชีมูลนิธิหรือหนังสือให้อำนาจจัดตั้ง"]]', '[["รายการเปลี่ยนแปลง", "คณะกรรมการบริหารเริ่มแรก"], ["มูลนิธินี้ได้รับอนุญาตให้จดทะเบียนจัดตั้ง", "นิติบุคคล"]]', NULL, NULL, 'เอกสารจัดตั้งมูลนิธิ', false, true, 38, '{"requirePreviousCategory": "เอกสารจัดตั้งมูลนิธิ"}', '2025-12-17 16:37:33.778651', '2025-12-17 17:24:11.345264');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (39, ' หนังสือให้อำนาจและรายละเอียดการเปลี่ยนแปลง(เปลี่ยนแปลง)', '[["ม.น. 2", "หนังสือให้อำนาจจัดตั้ง"], ["บัญชีมูลนิธิหรือหนังสือให้อำนาจจัดตั้ง"]]', '[["รายการเปลี่ยนแปลง", "คณะกรรมการบริหารเริ่มแรก"], ["มูลนิธินี้ได้รับอนุญาตให้จดทะเบียนจัดตั้ง", "นิติบุคคล"]]', NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 39, '{"blockPreviousCategory": "เอกสารจัดตั้งมูลนิธิ"}', '2025-12-17 16:38:08.687013', '2025-12-17 17:25:21.187033');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (1, 'ตราสาร', '[["ข้อบังคับ", "หมวดที่", "เครื่องหมาย"], ["ข้อบังคับ", "หมวดที่ 1", "ข้อ 1"], ["ข้อบังคับ", "มูลนิธิ", "เครื่องหมาย และที่ตั้งสำนักงาน"], ["มูลนิธิ", "หมวดที่ 1", "ข้อ 1", "เครื่องหมาย"], ["หมวดที่ 1", "ข้อเครื่องหมาย", "มูลนิธินี้ชื่อว่า"], ["ตราสาร", "มูลนิธิ", "เครื่องหมาย", "ข้อ 1"], ["ตราสาร", "มูลนิธิ", "หมวดที่ 1", "เครื่องหมาย"], ["ตราสาร", "หมวดที่ 1", "ข้อ 1", "เครื่องหมาย"]]', '[["บทเบ็ดเตล็ด", "ลงชื่อ", "ผู้จัดทำข้อบังคับ"], ["บทเบ็ดเตล็ด", "ลงนาม", "ผู้จัดทำข้อบังคับ"], ["หมวดที่ 12", "บทเบ็ดเตล็ด"], ["ลงชื่อ", "ผู้จัดทำข้อบังคับ", "ประธานกรรมการมูลนิธิ"], ["ลงนาม", "ผู้จัดทำข้อบังคับ", "ประธานกรรมการมูลนิธิ"], ["หมวดที่ 12", "บทเบ็ดเตล็ด", "ลงชื่อ"], ["สำเนาตราสารฉบับที่ได้รับอนุญาต"], ["บทเบ็ดเตล็ด", "ลงนาม", "ผู้จัดทำตราสาร"], ["บทเปิดเทล็ด", "ลงนาม", "ผู้จัดทำตราสาร"], ["หมวดที่ 12", "บทเปิดเทล็ด"], ["ลงนาม", "ผู้จัดทำตราสาร"], ["ลงนาม", "ผู้จัดทำตราสาร", "สำเนาตราสาร"], ["สำเนาตราสารฉบับที่ได้รับอนุญาต", "จดทะเบียน"], ["หมวดที่ 12", "บทบัญญัติ", "ลงนาม"], ["บทบัญญัติ", "ลงนาม", "ผู้จัดทำตราสาร"]]', '[["ฉบับที่ 2"], ["ฉบับที่ 3"], ["แก้ไข"], ["เปลี่ยนแปลง"]]', NULL, NULL, false, true, 0, NULL, '2025-12-17 16:24:12.294178', '2025-12-17 17:22:23.855421');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (7, 'ประกาศนายทะเบียนจัดตั้งมูลนิธิ', '[["ประกาศนายทะเบียนมูลนิธิ", "จดทะเบียนจัดตั้ง"], ["ประกาศนายทะเบียน", "เรื่อง จดทะเบียนจัดตั้ง"]]', '[["ได้อนุญาตให้จดทะเบียนจัดตั้งมูลนิธิรายนี้แล้ว"], ["ประกาศ ณ วันที่", "นายทะเบียน"]]', NULL, NULL, 'เอกสารจัดตั้งมูลนิธิ', false, true, 6, NULL, '2025-12-17 16:24:12.324632', '2025-12-17 17:22:23.949262');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (13, 'คำขอจดทะเบียนการแต่งตั้งกรรมการของมูลนิธิขึ้นใหม่ทั้งชุด', '[["คำขอจดทะเบียนการแต่งตั้งกรรมการ", "ข้าพเจ้า", "บัตรประจำตัวประชาชน"], ["คำขอจดทะเบียน", "แต่งตั้งกรรมการขึ้นใหม่", "ขอยืนคำขอ"], ["คำขอจดทะเบียนการแต่งตั้งกรรมการของมูลนิธิขึ้นใหม่ทั้งชุดหรือการเปลี่ยนแปลงกรรมการของมูลนิธิ"]]', '[["ความเห็นพนักงานเจ้าหน้าที่", "ลงชื่อ"], ["เอกสารและรายละเอียด", "แผนผังโดยสังเขป"], ["หนังสืออนุญาตจากเจ้าของ", "ให้ใช้สถานที่"], ["ความเห็นพนักงานเจ้าหน้าที่", "คำสั่งนายทะเบียน", "อนุญาต"], ["คำสั่งนายทะเบียน", "อนุญาต", "ลงชื่อ"]]', '[["ใบสำคัญ"], ["เรียน"], ["บันทึกข้อความ"]]', NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 12, NULL, '2025-12-17 16:24:12.331499', '2025-12-17 17:22:24.031367');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (40, 'ขออนุญาตจดทะเบียนแต่งตั้งกรรมการของมูลนิธิขึ้นใหม่ทั้งชุด', '[["ขออนุญาตจดทะเบียนแต่งตั้งกรรมการของมูลนิธิขึ้นใหม่ทั้งชุด"], ["ขออนุญาตจดทะเบียนแต่งตั้งกรรมการขึ้นใหม่ทั้งชุด", "นายทะเบียนมูลนิธิ"]]', NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', true, true, 40, NULL, '2025-12-17 17:19:25.680128', '2025-12-17 17:30:15.755295');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (18, 'บันทึกข้อความขอจดทะเบียนแต่งตั้งกรรมการขึ้นใหม่ทั้งชุด', '[["บันทึกข้อความ", "ขอจดทะเบียนแต่งตั้งกรรมการของมูลนิธิขึ้นใหม่ทั้งชุด"], ["บันทึกข้อความ", "ขอจดทะเบียนแต่งตั้งกรรมการขึ้นใหม่ทั้งชุด"]]', NULL, NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', true, true, 17, NULL, '2025-12-17 16:24:12.336583', '2025-12-17 17:30:17.131389');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (41, 'ประกาศนายทะเบียนจดทะเบียนแต่งตั้งกรรมการของมูลนิธิใหม่ทั้งชุด', '[["จดทะเบียนแต่งตั้งกรรมการของมูลนิธิขึ้นใหม่ทั้งชุด", "เรียน ปลัดกรุงเทพมหานคร"], ["จดทะเบียนแต่งตั้งกรรมการขึ้นใหม่ทั้งชุด", "นายทะเบียนมูลนิธิกรุงเทพมหานคร"]]', NULL, NULL, NULL, NULL, true, true, 41, NULL, '2025-12-17 17:21:38.039872', '2025-12-17 17:30:20.442993');
INSERT INTO public.templates (id, name, "firstPagePatterns", "lastPagePatterns", "firstPageNegativePatterns", "lastPageNegativePatterns", category, "isSinglePage", "isActive", "sortOrder", "contextRules", "createdAt", "updatedAt") VALUES (20, 'ใบสำคัญแสดงการจดทะเบียนแต่งตั้งกรรมการของมูลนิธิขึ้นใหม่ทั้งชุด', '[["ม.น. 4", "ใบสำคัญแสดงการจดทะเบียนแต่งตั้งกรรมการของมูลนิธิขึ้นใหม่ทั้งชุด"], ["ใบสำคัญแสดงการจดทะเบียนแต่งตั้งกรรมการของมูลนิธิขึ้นใหม่ทั้งชุด"]]', '[["ให้ไว้ ณ วันที่", "นายทะเบียนมูลนิธิ"], ["กรรมการและเลขานุการ", "ให้ไว้ ณ วันที่"]]', NULL, NULL, 'เอกสารเปลี่ยนแปลงมูลนิธิ', false, true, 19, NULL, '2025-12-17 16:24:12.338072', '2025-12-17 17:30:22.488863');


--
-- Name: templates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.templates_id_seq', 41, true);


--
-- PostgreSQL database dump complete
--

\unrestrict 9wH1cN6tQnXnKbcvYoIwsLbSUuquYKxCPgObK6KdnR2mas2He21AnqMibbD1TEI

